version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # 0 = only security PRs (security updates ignore this limit)
    open-pull-requests-limit: 0
    commit-message:
      prefix: "fix"
      include: "scope"
  - package-ecosystem: "npm"
    directory: "/packages/react"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    commit-message:
      prefix: "fix"
      include: "scope"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    commit-message:
      prefix: "chore"
      include: "scope"
