changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: New Operators
      labels:
        - operator
        - new-operator
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Maintenance
      labels:
        - chore
        - dependencies
        - maintenance
