name: publish

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Tag to publish (e.g. v1.0.1)"
        required: true

jobs:
  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tag
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.version }}

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24.x
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Publish to NPM
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build React package
        run: npm run build --workspace=packages/react

      - name: Publish React package to NPM
        run: npm publish --workspace=packages/react --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
